Update shellscript

diff --git a/shellscript b/shellscript
--- a/shellscript
+++ b/shellscript
@@ -148,3 +148,132 @@ ps -ef | grep nginx
 
 
 
+Local to s3
+
+#!/bin/bash
+echo "Enter the file name"
+read filename
+echo "Enter the s3 Bucket name"
+read bucket
+aws s3 cp $filename s3://$bucket/
+
+=================================
+Dynamically changing the servername with shell script
+#!/bin/bash
+echo "Enter your hostname"
+read servername
+echo "you are going to set hostname is $servername"
+echo "$servername" >/etc/hostname
+
+#privateip=$((ifconfig eth0 | grep -w 'inet' | awk '{print $2}'))
+privateip=$(hostname -I)
+echo "$privateip $servername" >>/etc/hosts
+hostname -F /etc/hostname
+echo "your servername is :`hostname` "
+echo "your servername is :$HOSTNAME "
+
+=================================
+
+
+
+Enabling epel
+#!/bin/bash
+wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
+#curl http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -o epel-release-latest-7.noarch.rpm
+rpm -ivh epel-release-7*.rpm
+
+
+yum update
+
+yum install nginx -y
+ 
+ /etc/nginx
+ main file : /etc/nginx/nginx.conf
+
+ /usr/share/nginx/html/---->webstefiles
+
+ systemctl start nginx
+ systemctl stop nginx
+ systemctl enable nginx
+
+
+netstat -anlp | grep ":80"
+
+ps -ef | grep nginx
+===============================
+
+#!/bin/bash
+
+oslist=filename
+
+for serername in `cat /opt/scripts/serverlist`
+#Connecting to remote servers
+
+ssh devopsadmin@$servername
+#redirecting output of uname into filename
+uname >>$oslist
+
+done
+
+#priting the os list file
+cat $oslist
+#send the email with subject with attachment(filename)
+mail -s "OS lists" someone@somewhere.com -a $oslist
+
+
+ping script
+=============
+#!/bin/sh
+ 
+# -q quiet
+# -c nb of pings to perform
+echo "enter the name"
+read name
+ping -q -c5 $name > /dev/null
+ 
+#check previous command successful or not
+if  [$? -eq 0 ]
+then
+  echo "ok"
+fi
+
+
+
+
+
+  #!/bin/bash
+  webs=/home/devopsadmin/scripts/serverslist
+
+ for name in `cat $webs`; do 
+  ping -q -c5 $name > /dev/null
+
+  if [ $? -eq 0 ]; then
+      echo "$name --> OK "
+  else
+      echo "$name-->FAIL"
+  fi
+done
+
+
+
+
+
+
+#!/bin/bash
+for i in `sec 0 255`; do 
+    ping -c 1 $i >/dev/null 2>&1 
+    if [ "$?" = "0" ]; then 
+echo -n "up" 
+else echo -n "down" 
+    fi
+done
+
+======================================
+sshlogin
+[root@bastionserver devopsadmin]# cat /tmp/login.sh
+#!/bin/bash
+echo "Connecting to servers"
+echo "Enter server you want to connect"
+read servername
+ssh -i /tmp/sshlogin.pem ec2-user@$servername
+[root@bastionserver devopsadmin]# 
